### ISSUE TITLE
Filename matcher doesn't work?

### ISSUE THREAD

**Issue by The-Compiler** [jayvdb/flake8-putty#2]
I'm probably doing something wrong, but I can't figure out what it is :wink:

I'm using this in my config:

```
putty-ignore =
    test_*.py : +D100,D101,D202
```

However I still get those messages, e.g.:

```
./tests/unit/misc/test_sessions.py:48:1: D101 Missing docstring in public class
```

I tried different variations (`test_*`, `tests/*/*/test_*.py`, etc.) but I didn't get any of those to work. Any idea why?

**Comment by jayvdb** [comment]
You need to use file pattern `*/test_*.py`

The file selecter uses `fnmatch.fnmatch` with only a few improvements.

```python
>>> import fnmatch
>>> fnmatch.fnmatch('foo/test_bar.py', '*.py')
True
>>> fnmatch.fnmatch('foo/test_bar.py', 'test_*.py')
False
>>> fnmatch.fnmatch('foo/test_bar.py', 'foo/test_*.py')
True
>>> fnmatch.fnmatch('foo/test_bar.py', '*/test_*.py')
True
>>> fnmatch.fnmatch('foo/baz/test_bar.py', '*/test_*.py')
True
```

Currently the improvements are:
1. strip leading `./` , or `.\\` on windows
2. patterns ending with `/` are used as exact prefix matches, so `a/b/` matches anything in the `a/b` directory and sub-directories.  this doesnt use `os.sep`, so it only works on Unix.

We could add another one to catch your scenario:

If the pattern doesn't contain a `/`, do `fnmatch` on the filename only.

However that would mean it isnt possible to use pattern `test_*.py` to only match `test_foo.py` and `test_bar.py` and not match `foo/test_bar.py`.  With a little more complexity, this scenario could be supported by allowing the pattern `./test_*.py` to bypass the suffix match.

**Comment by The-Compiler** [comment]
So `tests/*/*/test_*.py` should have worked with my example above, no? I agree your proposal would make sense.

**Comment by jayvdb** [comment]
Yes, `tests/*/*/test_*.py` should have worked .  I've added tests to confirm that works: 54cd2c5fc7

**Comment by The-Compiler** [comment]
Hm, odd. I'll try this again later this week and come back to you.

**Comment by The-Compiler** [comment]
Indeed that seems to work fine - I guess I just had too many errors to notice some where gone.

**Comment by CleanCut** [comment]
So, why does `*` not work, but `*.py` will?  I was trying to add a global ignore list to your flake8-putty contribution to green, but the flake8 ignore setting was ignored, and something like this is ignored as well:

    * : +C901

But after reading this thread, I tried this, which works:

    *.py :+C901

**Comment by jayvdb** [comment]
I think it is too early to give ´*´ to be a filename rule. There may be better uses for it.

**Comment by jayvdb** [comment]
I tested `tests/*/test_*.py : +D100,D101,D401` in the qutebrowser repo, and it [[https://travis-ci.org/jayvdb/qutebrowser/builds/121606076|worked]] as expected, so closing this ticket.

Further regarding `* : xxx` , to ignore C901 unconditionally it can be added to `flake8` 's `ignore` list.  i.e. `flake8-putty` isnt needed for unconditional ignores.  But as you've demonstrated, an almost unconditional ignore `*.py : x` does work.

I've raised #8 and #9 to track tangential ideas raised in this ticket.
